ARG PHP_EXTENSIONS="imagick"

FROM thecodingmachine/php:8.2-v4-fpm as php

COPY --from=composer:2.5.8 --chown=docker:docker /usr/bin/composer /usr/bin/composer

WORKDIR /application

COPY --chown=docker:docker ./ /application
COPY --chown=docker:docker ./.env /application/.env
COPY --chown=docker:docker ./docker/php/php-ini-overrides.ini /etc/php/8.2/fpm/conf.d/99-overrides.ini

RUN composer install --no-scripts --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs
RUN composer dump-autoload --optimize --classmap-authoritative

CMD ["etc/application/symfony/start"]

FROM nginx:1.23.2-alpine AS nginx

WORKDIR /application
