version: "3"
services:
  tilesets_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile
    entrypoint: "./docker-entrypoint-dev"
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini
      # - ./etc/infrastructure/php/conf.d/xdebug.ini:/etc/php/8.2/fpm/conf.d/20-xdebug.ini
      # - ./etc/infrastructure/php/conf.d/xdebug.ini:/etc/php/8.2/cli/conf.d/20-xdebug.ini
      # - /tmp/xdebug:/tmp/xdebug
    environment:
      PHP_EXTENSION_IMAGICK: 1
    networks:
      proxy:
        ipv4_address: 10.200.31.3

  tilesets_nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tilesets_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tilesets_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.tilesets_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.31.2

networks:
  proxy:
    external: true
