version: "3"
services:
  tilesets_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile-prod
    environment:
      PHP_EXTENSION_IMAGICK: 1
    working_dir: /application
    volumes:
      - ./src/resources:/application/src/resources
    networks:
      proxy:
        ipv4_address: 10.200.31.2

  tilesets_nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile-prod
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tilesets_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tilesets_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.tilesets_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.31.3

networks:
  proxy:
    external: true
