#!/usr/bin/env bash

composer install --no-scripts --no-interaction
composer dump-autoload
mkdir -p /application/src/resources/tilesets
ln -sf /application/src/resources/tilesets /application/public/tilesets

php-fpm
