controllers:
    resource:
        path: ../src/Cut/UI/Http/
        namespace: App\Cut\UI\Http
    type: attribute

merge_routes:
  resource:
    path: ../src/Merge/UI/Http
    namespace: App\Merge\UI\Http
  type: attribute

tiles_routes:
  resource:
    path: ../src/Tiles/UI/Http
    namespace: App\Tiles\UI\Http
  type: attribute
