parameters:
  tilesetsPath: '%kernel.project_dir%/src/resources/tilesets'
  resourcesPath: '%kernel.project_dir%/src/resources'
  websiteUrl: '%env(WEBSITE_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $tilesetsPath: '%tilesetsPath%'
      $resourcesPath: '%resourcesPath%'
      $websiteUrl: '%websiteUrl%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
      - '../src/resources/*'
